name: 'Auto Review'
description: 'Automatically review PRs'
icon: check-circle
color: yellow
inputs:
  GITHUB_TOKEN:
    description: 'Personal github token'
    required: true
  EVENT_TYPE:
    description: 'Type of event has been APPROVE, COMMENT and REQUEST_CHANGES.'
    required: false
    default: 'APPROVE'
  MESSAGE:
    description: 'Message for approve.'
    required: false
    default: 'Success approve. Enjoy 🏳️‍🌈🎉.'
runs:
  using: 'node12'
  main: 'dist/index.js'
