name: Build

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download & Build
      run: npm run build

    - name: Dist
      uses: actions/upload-artifact@v2
      with:
        name: dist/index.js
        path: dist/index.js 